---

- name: 'Create directory for container data'
  file:
    path: "{{ docker_data_dir }}/portainer_data"
    state: 'directory'

# Look at portainer role on hps for inspiration


# - name: 'Deploy Portainer'
#   docker_swarm_service:
#     name: 'portainer'
#     image: 'portainer/portainer'
#     command: '/portainer -H tcp://tasks.portainer_agent:9001 --tlsskipverify'
#     env:
#       - 'AGENT_CLUSTER_ADDR=tasks.portainer_agent'
#     mounts:
#       - source: "{{ docker_data_dir }}/portainer_data"
#         target: '/data'
#         type: 'bind'
#     networks:
#       - 'traefik_backend'
#       - 'portainer_agent_network'
#     labels:
#       traefik.http.routers.portainer.rule: "Host(`{{ portainer_app_name }}.{{ traefik_domain }}`)"
#       traefik.http.routers.portainer.tls: "true"
#       traefik.http.services.portainer.loadbalancer.server.port: '9000'
#     mode: 'replicated'
#     replicas: 1
#     restart_config:
#       condition: "{{ restart_condition }}"
#     placement:
#       constraints:
#         - 'node.role == manager'
#     user: null
