---
- name: 'Add traefik_backend network'
  docker_network:
    name: 'traefik_backend'
    driver: 'overlay'

- name: 'Create directory for data'
  file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    state: 'directory'
  loop:
    - 'traefik_data'
  loop_control:
    loop_var: 'dir'

- name: 'Copy traefik config into place'
  template:
    src: 'templates/traefik.toml.j2'
    dest: '{{ docker_data_dir }}/traefik_data/traefik.toml'
    mode: '0644'

- name: 'Deploy Traefik'
  docker_container:
    name: 'traefik'
    image: 'traefik:v2.1'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.entrypoints: 'http'
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_domain }}`)"
      traefik.http.middlewares.traefik-auth.basicauth.users: "{{ traefik_auth_credentials }}"
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: 'https'
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: 'true'
      traefik.http.routers.traefik.middlewares: 'https-redirect'
      traefik.http.routers.traefik-secure.entrypoints: 'https'
      traefik.http.routers.traefik-secure.rule: "Host(`{{ traefik_domain }}`)"
      traefik.http.routers.traefik-secure.middlewares: 'traefik-auth'
      traefik.http.routers.traefik-secure.tls: 'true'
      traefik.http.routers.traefik-secure.service: 'api@internal'
      traefik.http.services.traefik.loadbalancer.server.port: '8080'
    mounts:
      - source: '{{ docker_data_dir }}/traefik_data/traefik.toml'
        target: '/traefik.toml'
        type: 'bind'
        readonly: yes
      - source: '{{ docker_data_dir }}/certbot/cert.pem'
        target: '/cert.pem'
        type: 'bind'
        readonly: yes
      - source: '{{ docker_data_dir }}/certbot/key.pem'
        target: '/key.pem'
        type: 'bind'
        readonly: yes
    networks:
      - 'traefik_backend'
    mode: 'global'
    restart_config:
      condition: "{{ restart_condition }}"
    publish:
      - published_port: 80
        target_port: 80
      - published_port: 443
        target_port: 443
      - published_port: 8080
        target_port: 8080
    user: null
